- name: create backup dir
  ansible.builtin.file:
    path: /apps/
    state: directory

- name: copy and unarchive the backup file
  ansible.builtin.unarchive:
    src: backup.zip
    dest: /apps/jenkins_backup/

- name: change ownership for backup file
  file: dest=/apps/ owner=jenkins group=jenkins mode=u=rwX,g=rX,o=rX recurse=yes
