- name: create backup dir
  ansible.builtin.file:
    path: /apps/
    state: directory

- name: copy and unarchive the backup file
  ansible.builtin.unarchive:
    src: backup.zip
    dest: /apps/jenkins_backup/