- name: copy and unarchive the backup file
  ansible.builtin.unarchive:
    src: backup.tar.gz
    dest: /tmp

- name: Copy Backup Content
  ansible.builtin.copy:
    src: /tmp/var/lib/jenkins/
    dest: /var/lib/jenkins/
    remote_src: yes