---
- name: "disable SElinux temperoraly on all instances"
  hosts: all
  become: true
  tasks: 
    - name: disable SElinux temperoraly
      ansible.builtin.shell:
        cmd: setenforce Permissive