USER: node
COMPONENT: node-app
APP_KEYS : "{{lookup('amazon.aws.aws_secret', 'spec/keys', region='us-east-1')}}"
APP_VERSION : 1.0
ENV : test
DB_PASS: 123Chaitu
DB_USER: chaitu
DB_URL: cluster0.wdtudby.mongodb.net
LOG_FILE: '/var/log/{{COMPONENT}}.log'
APP_NAME: '{{COMPONENT}}'
SERVICE: '{{COMPONENT}}'
SOURCE: 'application'
TAGS: "env:{{ENV}},version:{{APP_VERSION}}"