- name: when git dwonload is defined
  block:
    - name: Download and UnZip the Application Content
      ansible.builtin.unarchive:
        src: https://github.com/ChaitanyaChandra/app/archive/main.zip
        dest: /tmp
        remote_src: yes

    - name: Copy App Content
      ansible.builtin.copy:
        src: /tmp/app-main/
        dest: /home/{{USER}}/{{COMPONENT}}/
        remote_src: yes
      become_user: "{{USER}}"

    - name: Install packages based on package.json.
      shell: npm install
      args:
        chdir: "/home/{{USER}}/{{COMPONENT}}"
      become_user: "{{USER}}"
  when: GIT_DOWNLOAD is defined

 - name: when GIT_DOWNLOAD is not defined
   block:
     - name: Download nodejs artifacts  from Nexus
       ansible.builtin.get_url:
         url: http://nexus-dev.chaitu.org:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
         dest: /tmp
         username: "{{APP_KEYS.APP_USER}}"
         password: "{{APP_KEYS.APP_PASS}}"

     - name: Unzip {{COMPONENT}}
       ansible.builtin.unarchive:
         src: /tmp/{{COMPONENT}}-{{APP_VERSION}}.zip
         dest: /home/{{USER}}/{{COMPONENT}}/
         remote_src: yes
       become_user: "{{USER}}"
   when: GIT_DOWNLOAD is not defined