- name: Install NodeJS dependencies 
  ansible.builtin.yum:
    name:
      - epel-release
      - unzip
      - nodejs
      - npm
    state: present

- name: Application User Setup and Download App Files
  import_tasks: app-user-setup.yml

- name: Install packages based on package.json.
  shell: npm install
  args:
    chdir: "/home/{{USER}}/{{COMPONENT}}"
  become_user: "{{USER}}"
  when: GIT_DOWNLOAD is defined

#- name: Install packages based on package.json.
#  community.general.npm:
#    path: /home/{{USER}}/{{COMPONENT}}
#  become_user: "{{USER}}"

- name:  Copy {{COMPONENT}} filebeat and rsyslog config
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'systemd.service' , dest: '/etc/systemd/system/{{COMPONENT}}.service' }
    - { src: 'rsyslog.conf' , dest: '/etc/rsyslog.d/{{COMPONENT}}.conf' }

- name: Start {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  notify: restart Service