- name: when git dwonload is defined
  block:
    - name: Download and UnZip the Application Content
      ansible.builtin.unarchive:
        src: https://github.com/ChaitanyaChandra/status-app/archive/main.zip
        dest: /tmp
        remote_src: yes

    - name: Copy App Content
      ansible.builtin.copy:
        src: /tmp/status-app-main/
        dest: /home/{{USER}}/{{COMPONENT}}/
        remote_src: yes
      become_user: "{{USER}}"

    - name: Install Maven Dependencies
      ansible.builtin.shell: rm -rf target ; mvn clean package && mv target/{{COMPONENT}}-1.0-SNAPSHOT.jar {{COMPONENT}}-1.0-SNAPSHOT.jar
      args:
        chdir: /home/{{USER}}/{{COMPONENT}}/
      become_user: "{{USER}}"
  when: GIT_DOWNLOAD is defined

- name: when GIT_DOWNLOAD is not defined
  block:
    - name: Download nodejs artifacts  from Nexus
      ansible.builtin.get_url:
        url: http://nexus.chaitu.org:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
        dest: /tmp
        username: "{{APP_KEYS.APP_USER}}"
        password: "{{APP_KEYS.APP_PASS}}"

    - name: Unzip {{COMPONENT}}
      ansible.builtin.unarchive:
        src: /tmp/{{COMPONENT}}-{{APP_VERSION}}.zip
        dest: /home/{{USER}}/{{COMPONENT}}/
        remote_src: yes
      become_user: "{{USER}}"

    - name: Rename file
      shell: /home/{{USER}}/{{COMPONENT}}/{{COMPONENT}}.jar /home/{{USER}}/{{COMPONENT}}/{{COMPONENT}}-1.0-SNAPSHOT.jar
  when: GIT_DOWNLOAD is not defined