- name: Install Java & mvn
  ansible.builtin.yum:
    name: 
      - java
      - maven
    state: installed

- name: Application User Setup and Download App Files
  import_tasks: app-user-setup.yml



- name:  Copy {{COMPONENT}} systemd and rsyslog config
  template: src={{ item.src }} dest={{ item.dest }}
  loop:
    - { src: 'systemd.service' , dest: '/etc/systemd/system/{{COMPONENT}}.service' }
    - { src: 'rsyslog.conf' , dest: '/etc/rsyslog.d/{{COMPONENT}}.conf' }

- name: Start {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  notify: restart Service