- name: restart Service
  ansible.builtin.systemd:
    name: datadog-agent
    state: restarted

- name: restart Services
  systemd:
    name: "{{ item.service }}"
    state: restarted
  ignore_errors: yes
  loop:
    - { service: 'rsyslog' }
    - { service: 'nginx' }