- name: Get existing credentials
  uri:
    url: "{{URL}}/credentials/store/system/domain/_/api/json?tree=credentials[id]"
    method: GET
    user: "{{ APP_KEYS.APP_USER }}"
    password: "{{ APP_KEYS.APP_PASS }}"
    force_basic_auth: yes
    follow_redirects: all
  register: credentials

- name : print
  debug: credentials
#- name: Delete secret
#  uri:
#    url: "{{ URL }}/credentials/store/system/domain/_/credential/{{ item.id }}/doDelete"
#    method: POST
#    user: "{{ APP_KEYS.APP_USER }}"
#    password: "{{ APP_KEYS.APP_PASS }}"
#    force_basic_auth: yes
#    follow_redirects: all
#  loop: "{{ credentials.json.credentials }}"