- name: Delete previous Jenkins secret
  uri:
    url: "{{ URL }}/credentials/store/system/domain/_/credential/{{ SECRET_ID }}/doDelete"
    method: POST
    user: "{{ APP_KEYS.APP_USER }}"
    password: "{{ APP_KEYS.APP_PASS }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    return_content: yes
  register: secret_delete
  ignore_errors: true