- name: Delete Jenkins secret
  hosts: jenkins
  tasks:
    - name: Get existing credentials
      uri:
        url: "{{URL}}/credentials/store/system/domain/_/api/json?tree=credentials[id]"
        method: GET
        user: "{{ APP_KEYS.APP_USER }}"
        password: "{{ APP_KEYS.APP_PASS }}"
        status_code: 200
      register: credentials

    - name: Delete secret
      uri:
        url: "{{ URL }}/credentials/store/system/domain/_/credential/{{ item.id }}/doDelete"
        method: POST
        user: "{{ APP_KEYS.APP_USER }}"
        password: "{{ APP_KEYS.APP_PASS }}"
        status_code: 200
      loop: "{{ credentials.json.credentials }}"