- name: Create Jenkins secret
  uri:
    url: "{{ URL }}/credentials/store/system/domain/_/createCredentials"
    method: POST
    user: "{{ APP_KEYS.APP_USER }}"
    password: "{{ APP_KEYS.APP_PASS }}"
    body: "{{
      '''
      {
        \"\": \"0\",
        \"credentials\": {
          \"scope\": \"GLOBAL\",
          \"id\": \"{{ SECRET_ID }}\",
          \"username\": \"{{ APP_KEYS.APP_USER }}\",
          \"password\": \"{{ APP_KEYS.APP_PASS }}\",
          \"description\": \"{{ secret_description }}\",
          \"$class\": \"com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl\"
        }
      }
      '''
    }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    return_content: yes
  register: secret_create

- name: Create SSH secret
  jenkins_secret:
    name: "ssh-key"
    secret: "{{ SSH_KEYS ) }}"
    secret_type: "ssh-private-key"
    jenkins_url: "https://jenkins.chaitu.net"
    user: "{{ APP_KEYS.APP_USER }}"
    password: "{{ APP_KEYS.APP_PASS }}"