- name: remove old dir
  ansible.builtin.file:
    path: ~/.ssh/{{item.file}}
    state: absent
  loop:
    - { 'file': 'key.pem' }
    - { 'file': 'config' }

- name: create ssh dir 
  ansible.builtin.file:
    path: ~/.ssh/
    state: directory

- name: Retrieve the details
  ansible.builtin.include_tasks: r53.yml
  loop: 
    - {'COMPONENT': 'jenkins'}
    - {'COMPONENT': 'sonar'}
    - {'COMPONENT': 'nexus'}
    - {'COMPONENT': 'workstation'}

- name: Add a line to a file if the file does not exist
  ansible.builtin.lineinfile:
    path: ~/.ssh/key.pem
    line: "{{SSH_KEY}}"
    create: yes
    mode: '0400'
