- name: Application User Setup and Download App Files
  import_tasks: perameters.yml

- name: Install DataDog.
  ansible.builtin.shell: |
      export DD_API_KEY={{API_KEY.DD_API_KEY}}
      export DD_SITE="{{ lookup('aws_ssm', 'spec.DD_SITE', region='us-east-1' ) }}"
      bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)"
  ignore_errors: yes

- name: Update MongoDB Listen address
  ansible.builtin.replace:
    path: /etc/datadog-agent/datadog.yaml
    regexp: '# logs_enabled: false'
    replace: 'logs_enabled: true'