#- name: Application User Setup and Download App Files
#  import_tasks: perameters.yml

- name: Install DataDog.
  ansible.builtin.shell: |
      export DD_API_KEY={{API_KEY.DD_API_KEY}}
      export DD_SITE="datadoghq.com"     # export DD_SITE="{{ lookup('aws_ssm', 'spec.DD_SITE', region='us-east-1' ) }}"    
      bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)"

- name: enable logs in datadog.yml
  ansible.builtin.replace:
    path: /etc/datadog-agent/datadog.yaml
    regexp: '# logs_enabled: false'
    replace: 'logs_enabled: true'
  notify: restart Service

- name: Creates directory for integration
  ansible.builtin.file:
    path: /etc/datadog-agent/conf.d/custom_{{ APP_NAME }}.d
    state: directory

- name: log file permissions for datadog.
  ansible.builtin.shell: |
      sudo rm -rf {{ LOG_FILE }}; touch {{ LOG_FILE }}; sudo chown -R dd-agent:dd-agent {{ LOG_FILE }}
  ignore_errors: yes
  notify: restart Services

- name: place integration files
  ansible.builtin.template: src='conf.yml' dest='/etc/datadog-agent/conf.d/custom_{{ APP_NAME }}.d/conf.yml'
  notify: restart Service