- name: Create Parameters
  hosts: localhost
  tasks:
    - name: Update a Parameter
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        string_type: "String"
        value: "{{item.value}}"
        overwrite_value: "always"
      loop:
        - { name: "spec.DD_SITE", value: "datadoghq.com"}

- name: Install DataDog.
  ansible.builtin.shell: bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"
  environment:
    DD_AGENT_MAJOR_VERSION=7 
    DD_API_KEY={{API_KEY.DD_API_KEY}}  # using aws secrets manager, created phycally 
    DD_SITE="{{ lookup('aws_ssm', 'spec.DD_SITE', region='us-east-1' ) }}" # using perameter store, created above

- name: Update MongoDB Listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '# logs_enabled: false'
    replace: 'logs_enabled: true'