- name: Application User Setup and Download App Files
  import_tasks: perameters.yml

- name: Install DataDog.
  ansible.builtin.shell: bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)"
  environment:
    DD_API_KEY:{{API_KEY.DD_API_KEY}}
    DD_SITE:"{{ lookup('aws_ssm', 'spec.DD_SITE', region='us-east-1' ) }}"

- name: Update MongoDB Listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '# logs_enabled: false'
    replace: 'logs_enabled: true'