- name: Update a Parameter
  community.aws.ssm_parameter:
    name: "{{item.name}}"
    string_type: "String"
    value: "{{item.value}}"
    overwrite_value: "always"
  loop:
    - { name: "spec.DD_SITE", value: "datadoghq.com"}