apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null  # na
  labels:
    app: spec-deployment    # label to attach the service
  name: spec-deployment     # name of the deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app   # match label of container
  strategy: {}
  template:
    metadata:
      creationTimestamp: null   # na
      labels:
        app: node-app
    spec:
      containers:
        - image: chaituchowdary/node-app
          name: node-app
          resources: {}              # na
status: {}                           # na