---
apiVersion: v1
kind: Namespace
metadata:
  name: chandra


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spec-deployment     # name of the deployment
  namespace: chandra
  labels:
    app: spec-label        # label for service selector
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app        # match label of container in template
  template:
    metadata:
      labels:
        app: node-app     # label for deployment selector
        env: dev
    spec:
      containers:
        - image: chaituchowdary/node-app
          name: node-app

---
apiVersion: v1
kind: Service
metadata:
  name: spce-service
  namespace: chandra
  labels:
    env : dev
spec:
  selector:
    app: spec-label
  ports:
  - name: spec-svc-port     # name-of-service-port
    protocol: TCP
    port: 80                # port of host
    targetPort: 8080        # port of the pod/application